-- Supply Chain Command Center: Database Setup
-- Database: MANUFACTURING_SUPPLY_CHAIN

CREATE DATABASE IF NOT EXISTS MANUFACTURING_SUPPLY_CHAIN;

CREATE SCHEMA IF NOT EXISTS MANUFACTURING_SUPPLY_CHAIN.RAW;
CREATE SCHEMA IF NOT EXISTS MANUFACTURING_SUPPLY_CHAIN.CURATED;
CREATE SCHEMA IF NOT EXISTS MANUFACTURING_SUPPLY_CHAIN.AI;
CREATE SCHEMA IF NOT EXISTS MANUFACTURING_SUPPLY_CHAIN.ML;
CREATE SCHEMA IF NOT EXISTS MANUFACTURING_SUPPLY_CHAIN.SEARCH;
CREATE SCHEMA IF NOT EXISTS MANUFACTURING_SUPPLY_CHAIN.APP;

USE DATABASE MANUFACTURING_SUPPLY_CHAIN;
USE WAREHOUSE CORTEX;
