-- Supply Chain Command Center: Raw Tables
USE SCHEMA MANUFACTURING_SUPPLY_CHAIN.RAW;

CREATE OR REPLACE TABLE SHIPMENTS (
    SHIPMENT_ID VARCHAR,
    CONTAINER_ID VARCHAR,
    CARRIER_ID VARCHAR,
    ORIGIN_PORT_ID VARCHAR,
    DESTINATION_PORT_ID VARCHAR,
    SHIP_DATE TIMESTAMP,
    EXPECTED_ARRIVAL TIMESTAMP,
    ACTUAL_ARRIVAL TIMESTAMP,
    STATUS VARCHAR,        -- IN_TRANSIT, DELIVERED, STUCK, DELAYED
    DELAY_HOURS NUMBER,
    CARGO_VALUE NUMBER(12,2),
    COMMODITY_TYPE VARCHAR,
    PRIORITY VARCHAR
);

CREATE OR REPLACE TABLE CONTAINERS (
    CONTAINER_ID VARCHAR,
    CONTAINER_TYPE VARCHAR,
    SIZE_FT NUMBER,
    WEIGHT_KG NUMBER,
    TEMPERATURE_CONTROLLED BOOLEAN,
    LAST_KNOWN_PORT VARCHAR,
    LAST_SCAN_TIME TIMESTAMP
);

CREATE OR REPLACE TABLE CARRIERS (
    CARRIER_ID VARCHAR,
    CARRIER_NAME VARCHAR,
    ON_TIME_RATE NUMBER(5,2),
    FLEET_SIZE NUMBER,
    COVERAGE_REGIONS VARIANT,
    RISK_SCORE NUMBER(3,1)
);

CREATE OR REPLACE TABLE PORTS (
    PORT_ID VARCHAR,
    PORT_NAME VARCHAR,
    COUNTRY VARCHAR,
    REGION VARCHAR,
    CAPACITY_TEU NUMBER,
    CURRENT_UTILIZATION NUMBER(5,2),
    AVG_DWELL_TIME_HOURS NUMBER(5,1),
    CONGESTION_LEVEL VARCHAR
);

CREATE OR REPLACE TABLE WAREHOUSES (
    WAREHOUSE_ID VARCHAR,
    WAREHOUSE_NAME VARCHAR,
    LOCATION VARCHAR,
    CAPACITY_SQFT NUMBER,
    CURRENT_FILL_PCT NUMBER(5,2)
);

CREATE OR REPLACE TABLE SUPPLY_CHAIN_DOCS (
    DOC_ID VARCHAR,
    TITLE VARCHAR,
    CATEGORY VARCHAR,
    CONTENT VARCHAR,
    LAST_UPDATED TIMESTAMP
);
