-- Supply Chain Command Center: External Stage & Data Loading
USE SCHEMA MANUFACTURING_SUPPLY_CHAIN.RAW;

CREATE OR REPLACE STAGE SUPPLY_CHAIN_S3_STAGE
    URL = 's3://sg-manufacturing-demos-2026/supply-chain/'
    FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"');

-- Load from stage
COPY INTO SHIPMENTS FROM @SUPPLY_CHAIN_S3_STAGE/shipments/;
COPY INTO CONTAINERS FROM @SUPPLY_CHAIN_S3_STAGE/containers/;
COPY INTO CARRIERS FROM @SUPPLY_CHAIN_S3_STAGE/carriers/;
COPY INTO PORTS FROM @SUPPLY_CHAIN_S3_STAGE/ports/;
COPY INTO WAREHOUSES FROM @SUPPLY_CHAIN_S3_STAGE/warehouses/;
COPY INTO SUPPLY_CHAIN_DOCS FROM @SUPPLY_CHAIN_S3_STAGE/docs/;
