-- Supply Chain Command Center: Dynamic Tables
USE SCHEMA MANUFACTURING_SUPPLY_CHAIN.CURATED;

CREATE OR REPLACE DYNAMIC TABLE SHIPMENT_STATUS
    TARGET_LAG = '1 minute'
    WAREHOUSE = CORTEX
AS
SELECT
    s.SHIPMENT_ID,
    s.STATUS,
    s.DELAY_HOURS,
    s.CARGO_VALUE,
    s.COMMODITY_TYPE,
    s.PRIORITY,
    c.CARRIER_NAME,
    c.ON_TIME_RATE AS CARRIER_ON_TIME_RATE,
    p_orig.PORT_NAME AS ORIGIN_PORT,
    p_dest.PORT_NAME AS DESTINATION_PORT,
    p_orig.CONGESTION_LEVEL AS ORIGIN_CONGESTION,
    CASE
        WHEN s.DELAY_HOURS > 72 THEN 'CRITICAL'
        WHEN s.DELAY_HOURS > 24 THEN 'HIGH'
        WHEN s.DELAY_HOURS > 0 THEN 'MEDIUM'
        ELSE 'ON_TIME'
    END AS IMPACT_SCORE
FROM RAW.SHIPMENTS s
JOIN RAW.CARRIERS c ON s.CARRIER_ID = c.CARRIER_ID
JOIN RAW.PORTS p_orig ON s.ORIGIN_PORT_ID = p_orig.PORT_ID
JOIN RAW.PORTS p_dest ON s.DESTINATION_PORT_ID = p_dest.PORT_ID;

CREATE OR REPLACE DYNAMIC TABLE CARRIER_PERFORMANCE
    TARGET_LAG = '1 minute'
    WAREHOUSE = CORTEX
AS
SELECT
    c.CARRIER_ID,
    c.CARRIER_NAME,
    c.ON_TIME_RATE,
    COUNT(s.SHIPMENT_ID) AS TOTAL_SHIPMENTS,
    SUM(CASE WHEN s.STATUS = 'DELAYED' THEN 1 ELSE 0 END) AS DELAYED_SHIPMENTS,
    SUM(CASE WHEN s.STATUS = 'STUCK' THEN 1 ELSE 0 END) AS STUCK_SHIPMENTS,
    AVG(s.DELAY_HOURS) AS AVG_DELAY_HOURS,
    SUM(s.CARGO_VALUE) AS TOTAL_CARGO_VALUE
FROM RAW.CARRIERS c
JOIN RAW.SHIPMENTS s ON c.CARRIER_ID = s.CARRIER_ID
GROUP BY c.CARRIER_ID, c.CARRIER_NAME, c.ON_TIME_RATE;

CREATE OR REPLACE DYNAMIC TABLE PORT_CONGESTION
    TARGET_LAG = '1 minute'
    WAREHOUSE = CORTEX
AS
SELECT
    p.PORT_ID,
    p.PORT_NAME,
    p.COUNTRY,
    p.CURRENT_UTILIZATION,
    p.AVG_DWELL_TIME_HOURS,
    p.CONGESTION_LEVEL,
    COUNT(CASE WHEN s.STATUS = 'STUCK' THEN 1 END) AS STUCK_CONTAINERS,
    COUNT(CASE WHEN s.STATUS = 'DELAYED' THEN 1 END) AS DELAYED_SHIPMENTS
FROM RAW.PORTS p
LEFT JOIN RAW.SHIPMENTS s ON p.PORT_ID = s.ORIGIN_PORT_ID
GROUP BY p.PORT_ID, p.PORT_NAME, p.COUNTRY, p.CURRENT_UTILIZATION,
         p.AVG_DWELL_TIME_HOURS, p.CONGESTION_LEVEL;
