-- Supply Chain Command Center: ML Models
USE SCHEMA MANUFACTURING_SUPPLY_CHAIN.ML;

-- Transit time forecast input view
CREATE OR REPLACE VIEW TRANSIT_FORECAST_INPUT AS
SELECT
    DATE_TRUNC('day', s.SHIP_DATE) AS DS,
    p_orig.PORT_NAME || ' → ' || p_dest.PORT_NAME AS SERIES,
    AVG(DATEDIFF('hour', s.SHIP_DATE, COALESCE(s.ACTUAL_ARRIVAL, s.EXPECTED_ARRIVAL))) AS Y
FROM RAW.SHIPMENTS s
JOIN RAW.PORTS p_orig ON s.ORIGIN_PORT_ID = p_orig.PORT_ID
JOIN RAW.PORTS p_dest ON s.DESTINATION_PORT_ID = p_dest.PORT_ID
WHERE s.SHIP_DATE IS NOT NULL
GROUP BY DS, SERIES;

-- Transit Time Forecast Model
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST TRANSIT_TIME_MODEL(
    INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'TRANSIT_FORECAST_INPUT'),
    SERIES_COLNAME => 'SERIES',
    TIMESTAMP_COLNAME => 'DS',
    TARGET_COLNAME => 'Y'
);

-- Delay Anomaly Detection Model
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION DELAY_ANOMALY_MODEL(
    INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'TRANSIT_FORECAST_INPUT'),
    SERIES_COLNAME => 'SERIES',
    TIMESTAMP_COLNAME => 'DS',
    TARGET_COLNAME => 'Y'
);
